//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VisionSystemQin.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VISIONSYSTEMQIN_DIALOG      102
#define IDD_CALIBRATECAMERA             104
#define IDR_MAINFRAME                   128
#define IDD_VisionProcess               132
#define IDD_ImageProcess                133
#define IDD_ResultDisplay               134
#define IDB_BITMAP_BackDistance         136
#define IDB_BITMAP_DownDistance         137
#define IDB_BITMAP_ForwardDistance      138
#define IDB_BITMAP_LeftDistance         139
#define IDB_BITMAP_RightDistance        140
#define IDB_BITMAP_RotateXNi            141
#define IDB_BITMAP_RotateXShun          142
#define IDB_BITMAP_RotateYNi            143
#define IDB_BITMAP_RotateYShun          144
#define IDB_BITMAP_RotateZNi            145
#define IDB_BITMAP_RotateZShun          146
#define IDB_BITMAP_UpDistance           147
#define IDD_Mschart                     151
#define IDD_ResultReport                153
#define IDD_SPLASHSCREEN                156
#define IDB_BITMAP_AirRefuelling        158
#define IDB_BITMAP_Background           164
#define IDD_ShowMapX                    165
#define IDR_MENU_ShowMap                167
#define IDI_ICON1                       171
#define IDD_LongLatSetting              172
#define IDI_ICON_PLANE                  177
#define IDD_RecieverPlaneSetting        178
#define IDC_RADIO_VisionChessBoard      1003
#define IDC_RADIO_LocalChessBoard       1004
#define IDC_BUTTON_LoadLocalChessBoard  1005
#define IDC_EDIT_XCornorCount           1006
#define IDC_EDIT_YCornorCount           1007
#define IDC_EDIT_SquareSize             1008
#define IDC_EDIT_ChessDetectTimes       1009
#define IDC_RADIO_RGB2Gray              1010
#define IDC_CHECK_FPP                   1011
#define IDC_CHECK_UIG                   1012
#define IDC_CHECK_FAR                   1013
#define IDC_CHECK_ZTD                   1014
#define IDC_RADIO_RGB2HSV               1015
#define IDC_RADIO_RGB2YCrCb             1016
#define IDC_RADIO_RGB2HLS               1017
#define IDC_RADIO_RGB2Luv               1018
#define IDC_RADIO_RGB2XYZ               1019
#define IDC_COMBO_MethodChoose          1020
#define IDC_BUTTON_SettingBySystem      1021
#define IDC_BUTTON_StartCalibration     1022
#define IDC_BUTTON_ExitCalibration      1023
#define IDC_EDIT_Rotationr1             1024
#define IDC_EDIT_Rotationr2             1025
#define IDC_EDIT_Rotationr3             1026
#define IDC_EDIT_Intrinsiccy            1027
#define IDC_EDIT_Distortionk1           1028
#define IDC_EDIT_Distortionk2           1029
#define IDC_EDIT_Distortionp1           1030
#define IDC_EDIT_Distortionp2           1031
#define IDC_EDIT_Translationt1          1032
#define IDC_EDIT_Translationt2          1033
#define IDC_EDIT_Translationt3          1034
#define IDC_STATIC_CalibrationPicture   1035
#define IDC_STATIC_CalibrationTips      1036
#define IDC_EDIT_Intrinsicfx            1038
#define IDC_EDIT_Intrinsicfy            1039
#define IDC_EDIT_Intrinsiccx            1040
#define IDC_EDIT_youxiaoshuziweishu     1041
#define IDC_TAB_VisionImageResult       1046
#define IDC_BUTTON1                     1048
#define IDC_STATIC_VisionDisplay        1049
#define IDC_BUTTON_MschartCurveMarkDisplay 1049
#define IDC_BUTTON_CANCEL               1049
#define IDC_BUTTON_MschartCurveValueDisplay 1050
#define IDC_BUTTON_RecoverSystemSetting 1050
#define IDC_STATIC_Status               1051
#define IDC_STATIC_Loading              1052
#define IDC_EDIT_FontcolorR             1053
#define IDC_EDIT_FontcolorG             1054
#define IDC_EDIT_FontcolorB             1055
#define IDC_EDIT_FontX                  1056
#define IDC_BUTTON_DroguePositionDisplay 1057
#define IDC_BUTTON_Aplicatesetting      1058
#define IDC_EDIT_FontY                  1059
#define IDC_BUTTON_CameraDisplay        1060
#define IDC_BUTTON_RightDistance        1061
#define IDC_EDIT_CameraLeft             1062
#define IDC_EDIT_CameraTop              1063
#define IDC_EDIT_CameraDown             1064
#define IDC_EDIT_CameraRight            1065
#define IDC_BUTTON_CameraSetting        1066
#define IDC_BUTTON_UpDistance           1067
#define IDC_BUTTON_LeftDistance         1068
#define IDC_BUTTON_DownDistance         1069
#define IDC_RADIO_LeftBack              1070
#define IDC_RADIO_Back                  1071
#define IDC_RADIO_FarBack               1072
#define IDC_RADIO_UpBack                1073
#define IDC_BUTTON_ModeSetting          1074
#define IDC_EDIT_DistanceSensitivity    1075
#define IDC_EDIT_AngleSensitivity       1076
#define IDC_BUTTON_ForwardDistance      1077
#define IDC_BUTTON_BackDistance         1078
#define IDC_BUTTON_RotateYNi            1079
#define IDC_BUTTON_RotateXShun          1080
#define IDC_BUTTON_RotateYShun          1081
#define IDC_BUTTON_RotateXNi            1082
#define IDC_BUTTON_RotateZShun          1083
#define IDC_BUTTON_RotateZNi            1084
#define IDC_EDIT_PitchValue             1085
#define IDC_EDIT_RollValue              1086
#define IDC_EDIT_HeadingValue           1087
#define IDC_EDIT_Xposition              1088
#define IDC_EDIT_YPosition              1089
#define IDC_EDIT_ZPosition              1090
#define IDC_BUTTON_SystemSetting        1091
#define IDC_BUTTON_ClimateSetting       1092
#define IDC_RADIO_SunnyDay              1093
#define IDC_BUTTON_ClimateOpenLight     1094
#define IDC_EDIT_ResultTankerX          1095
#define IDC_EDIT_ResultTankerY          1096
#define IDC_RADIO_CloudyDay             1097
#define IDC_EDIT_ResultTankerZ          1097
#define IDC_RADIO_FogDay                1098
#define IDC_EDIT_ResultRecieverX        1098
#define IDC_RADIO_RainDay               1099
#define IDC_EDIT_ResultRecieverY        1099
#define IDC_RADIO_SnowDay               1100
#define IDC_EDIT_ResultRecieverZ        1100
#define IDC_EDIT_ResultProbeX           1101
#define IDC_EDIT_ResultProbeY           1102
#define IDC_EDIT_ResultProbeZ           1103
#define IDC_EDIT_ResultDrogueX          1104
#define IDC_EDIT_ResultDrogueY          1105
#define IDC_EDIT_ResultDrogueZ          1106
#define IDC_EDIT_ResultIntrinsicfx      1107
#define IDC_EDIT_ResultIntrinsicfy      1108
#define IDC_EDIT_ResultIntrinsiccx      1109
#define IDC_EDIT_ResultTankerPitch      1110
#define IDC_EDIT_ResultTankerRoll       1111
#define IDC_EDIT_ResultTankerHeading    1112
#define IDC_EDIT_ResultIntrinsiccy      1113
#define IDC_EDIT_ResultDistortionk1     1114
#define IDC_EDIT_ResultDistortionk2     1115
#define IDC_EDIT_ResultRecieverPitch    1116
#define IDC_EDIT_ResultRecieverRoll     1117
#define IDC_EDIT_ResultRecieverHeading  1118
#define IDC_EDIT_ResultDistortionp1     1119
#define IDC_EDIT_ResultDistortionp2     1120
#define IDC_EDIT_ResultRotationr1       1121
#define IDC_EDIT_ResultImageProcessDrogueX 1122
#define IDC_EDIT_ResultImageProcessDrogueY 1123
#define IDC_EDIT_ResultImageProcessDrogueZ 1124
#define IDC_EDIT_ResultPositioningAccuracyX 1125
#define IDC_EDIT_ResultPositioningAccuracyY 1126
#define IDC_EDIT_ResultPositioningAccuracyZ 1127
#define IDC_EDIT_ResultRotationr2       1128
#define IDC_EDIT_ResultRotationr3       1129
#define IDC_EDIT_ResultTranslationt1    1130
#define IDC_EDIT_ResultTranslationt2    1131
#define IDC_EDIT_ResultTranslationt3    1132
#define IDC_EDIT_Resultyouxiaoshuziweishu 1133
#define IDC_BUTTON_ChangeDisplatCoordiate 1134
#define IDC_BUTTON_ResultDynamicDisplay 1135
#define IDC_BUTTON_ImageStartDrogueDetect 1136
#define IDC_BUTTON_ResultReport         1136
#define IDC_BUTTON_DrogueDetectDisplay  1137
#define IDC_EDIT_ResultAtitudeHeading   1137
#define IDC_BUTTON_DrogueDetectDynamicDisplay 1138
#define IDC_EDIT_ResultAtitudePitch     1138
#define IDC_BUTTON_DrogueLocateDisplay  1139
#define IDC_BUTTON_DrogueLocateDynamicDisplay 1140
#define IDC_BUTTON_DrogueFollowDisplay  1141
#define IDC_BUTTON_DrogueFollowDynamicDisplay 1142
#define IDC_RADIO_GuassNoise            1143
#define IDC_RADIO_UniformNoise          1144
#define IDC_RADIO_SaltNoise             1145
#define IDC_SLIDER_GuassNoise           1146
#define IDC_EDIT_GuassNoise             1147
#define IDC_SLIDER_BrightAdjust         1148
#define IDC_EDIT_BrightAdjust           1149
#define IDC_SLIDER_ContrastAdjust       1150
#define IDC_EDIT_ContrastAdjust         1151
#define IDC_BUTTON_DilateErodeOrder     1152
#define IDC_COMBO_DetectMethod          1153
#define IDC_COMBO_FilteringMethod       1154
#define IDC_EDIT_DetectTotalTimes       1155
#define IDC_EDIT_DetectFailureTimes     1156
#define IDC_EDIT_Dilate                 1157
#define IDC_EDIT_Erode                  1158
#define IDC_EDIT_DrogueImageCoordiateX  1159
#define IDC_EDIT_DrogueImageCoordiateY  1160
#define IDC_EDIT_DrogueVisionCoordiateX 1161
#define IDC_EDIT_DrogueVisionCoordiateY 1162
#define IDC_EDIT9                       1163
#define IDC_EDIT_DrogueVisionCoordiateZ 1163
#define IDC_EDIT_MschartXAxisMarkMeanDistance 1163
#define IDC_COMBO_DrogueLocateSolveMethod 1164
#define IDC_EDIT_MschartXAxisMeanDistance 1164
#define IDC_EDIT_ImageIntrinsicfx       1165
#define IDC_EDIT_MschartYAxisMaxValue   1165
#define IDC_EDIT_ImageIntrinsicfy       1166
#define IDC_EDIT_DrogueVisionLocateX    1167
#define IDC_EDIT_DrogueVisionLocateY    1168
#define IDC_EDIT_MschartYAxisDisplaykeshujiange 1168
#define IDC_EDIT_DrogueVisionLocateZ    1169
#define IDC_EDIT_MschartXAxisMaxValue   1169
#define IDC_EDIT_FollowAreaLeft         1170
#define IDC_EDIT_MschartYAxisMeanDistance 1170
#define IDC_EDIT_FollowAreaRight        1171
#define IDC_PICTURE                     1171
#define IDC_EDIT_FollowAreaUp           1172
#define IDC_MSCHART1                    1172
#define IDC_EDIT_FollowAreaDown         1173
#define IDC_COMBO_MschartChooseCurve    1173
#define IDC_EDIT_InreaseAreaD           1174
#define IDC_COMBO_MschartChooseDisplayMode 1174
#define IDC_BUTTON_StartFollow          1175
#define IDC_EDIT_MschartTitleSetting    1175
#define IDC_BUTTON_LocateCurveDisplay   1176
#define IDC_EDIT_MschartBackgroundColorR 1176
#define IDC_EDIT_MschartBackgroundColorG 1177
#define IDC_BUTTON_LockCameraChannel    1177
#define IDC_EDIT_MschartBackgroundColorB 1178
#define IDC_EDIT_ImageAtitudeHeading    1178
#define IDC_EDIT_MschartCurveColorR     1179
#define IDC_EDIT_ImageAtitudePitch      1179
#define IDC_EDIT_MschartCurveColorG     1180
#define IDC_SLIDER_DisturbanceAdjust    1180
#define IDC_EDIT_MschartCurveColorB     1181
#define IDC_EDIT_MschartOtherColorR     1182
#define IDC_EDIT_MschartOtherColorG     1183
#define IDC_EDIT_MschartOtherColorB     1184
#define IDC_EDIT_MschartCurveWidth      1185
#define IDC_COMBO_MschartCurveMarkPattern 1186
#define IDC_EDIT_MschartCurveMarkColorR 1187
#define IDC_EDIT_MschartCurveMarkColorG 1188
#define IDC_EDIT_MschartCurveMarkColorB 1189
#define IDC_BUTTON_MschartSettingBySystem 1191
#define IDC_COMBO_MschartDynamicRefreshSpeed 1192
#define IDC_BUTTON_MschartSecondYAxisDisplay 1193
#define IDC_BUTTON_MschartApplySetting  1194
#define IDC_BUTTON_MschartExit          1195
#define IDC_EDIT_MschartYAxisMinValue   1196
#define IDC_LIST_ResultReport           1202
#define IDC_EDIT_CurrentFrame           1203
#define IDC_EDIT_LeaveDotNumber         1204
#define IDC_BUTTON_SaveResult           1205
#define IDC_STATIC_SystemTime           1206
#define IDC_EDIT_SystemSimulinkTimeH    1207
#define IDC_EDIT_SystemSimulinkTimeM    1208
#define IDC_EDIT_SystemSimulinkTimeS    1209
#define IDC_BUTTON_MapDisplay           1220
#define IDC_BUTTON_LongLatSetting       1221
#define IDC_RealTimeMAP                 1223
#define IDC_BUTTON_OnLarge              1224
#define IDC_BUTTON_OnSmall              1225
#define IDC_BUTTON_OK                   1225
#define IDC_BUTTON_OnMove               1226
#define IDC_EDIT_LongLatSettingLongLeftDu 1226
#define IDC_BUTTON_OnMiddle             1227
#define IDC_EDIT_LongLatSettingXLeft    1227
#define IDC_EDIT_LongLatSettingLongLeftFen 1228
#define IDC_EDIT_ShowMap_RecieverLong   1228
#define IDC_EDIT_LongLatSettingLongLeftMiao 1229
#define IDC_RADIO_ShowFree              1229
#define IDC_EDIT_LongLatSettingLongRightDu 1230
#define IDC_EDIT_ShowMap_RecieverLat    1230
#define IDC_EDIT_LongLatSettingLongRightFen 1231
#define IDC_EDIT_ShowMap_RecieverHeight 1231
#define IDC_EDIT_LongLatSettingLongRightMiao 1232
#define IDC_EDIT_ShowMap_RecieverSpeed  1232
#define IDC_EDIT_LongLatSettingLatLeftDu 1233
#define IDC_RADIO_LockLocation          1233
#define IDC_EDIT_LongLatSettingLatLeftFen 1234
#define IDC_BUTTON_test                 1234
#define IDC_EDIT_LongLatSettingLatLeftMiao 1235
#define IDC_EDIT_LongLatSettingLatRightDu 1236
#define IDC_BUTTON_ShowFlightLine       1236
#define IDC_EDIT_LongLatSettingLatRightFen 1237
#define IDC_BUTTON_StartTrackingLocation 1237
#define IDC_COMBO_StyleChoose           1237
#define IDC_EDIT_LongLatSettingLatRightMiao 1238
#define IDC_EDIT_StartRelativeX         1238
#define IDC_EDIT_LongLatSettingXRight   1239
#define IDC_EDIT_StartRelativeY         1239
#define IDC_BUTTON_RecieverPlaneMoniSetting 1239
#define IDC_EDIT_LongLatSettingYLeft    1240
#define IDC_EDIT_StartRelativeZ         1240
#define IDC_BUTTON_WelcomeInterfaceOnOff 1240
#define IDC_EDIT_LongLatSettingYRight   1241
#define IDC_EDIT_FinalRelativeX         1241
#define IDC_RADIO_LightWenliu           1241
#define IDC_BUTTON_LoadLastHistoryRecord 1242
#define IDC_EDIT_FinalRelativeY         1242
#define IDC_RADIO_MedianWenliu          1242
#define IDC_EDIT_FinalRelativeZ         1243
#define IDC_RADIO3                      1243
#define IDC_RADIO_ServeWenliu           1243
#define IDC_EDIT_RelativeSpeed          1244
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_MenuOnLarge                  32776
#define ID_MenuOnSmall                  32777
#define ID_MenuOnMove                   32778
#define ID_MenuOnMiddle                 32779
#define ID_MenuOnProjection             32780
#define ID_32781                        32781
#define ID_MENU_ShowWholeMap            32782
#define ID_32783                        32783
#define ID_MENUMouseControl             32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        179
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1242
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
